import os

GOOGLE_PLACES_API_KEY = os.environ.get("GOOGLE_PLACES_API_KEY", "")

print("CONFIG CHECK - API KEY LOADED:", bool(GOOGLE_PLACES_API_KEY))
print("CONFIG CHECK - API KEY LENGTH:", len(GOOGLE_PLACES_API_KEY))